name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env:
        MailSettings.Email: "${{ secrets.Email}}"
        SmtpServer: "${{ secrets.SMTPSERVER }}"
        MailSettings.Password: "${{ secrets.EmailPassword }}"
        MailSettings.Recipient: "${{ secrets.Recipient }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          SmtpServer: "${{ secrets.SMTPSERVER }}"
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "virtualdean"
          heroku_email: "${{ secrets.Recipient }}"
        env:
          SmtpServer: "${{ secrets.SMTPSERVER }}"
